= Codewars Solutions
:toc: left
:sectnums:
:sectlevels: 6
:toclevels: 6
:setclinks:
:icons: font
:webfonts:


:toc: left
:idprefix:
:idseparator: -

My code wars solutions in a few different languages.

== TypeScript and Deno

I use link:https://deno.land[Deno] to test and run the TypeScript solutions. Also be sure to

=== Running Tests With Deno

Change to the root directory of where these codewars solutions have been cloned, e.g:

----
$ cd /path/to/devhowto/src/codewars
----

The run all tests, or specific tests:

----
$ deno test --unstable 6kyu
$ deno test --unstable 6kyu/friend-foe
$ deno test --unstable 6kyu/friend-foe/friend-foe.spec
----

Check extra options with ``deno test  --help | less``.

=== Unstable APIs

We are making use of ``"deno.unstable": true`` in the project configuration and the use of the ``--unstable`` command line flag for running the tests because we are sometimes using unstable APIs, like link:https://deno.com/blog/v1.15#nested-testing-api[Nested Testing API] from Deno v1.15.

----
$ sed '' .vim/coc-settings.json
{
  "deno.enable": true,
  "deno.lint": true,
  "deno.unstable": true,
  "deno.importMap": "./import-map.json",
  "tsserver.enable": false
}
----

== JavaScript

TIP: Run `nvm use && npm install` inside the root directory of once.

Run tests for all challenges:

----
$ npm run test
----

To run the unit tests for a given challenge, run something like this:

----
$ npm run test path/to/<some-problem>.spec.js
----

To run in watch and verbose mode, add `-- --watch --verbose` to the commands bove. Ex:

----
$ npm run test 7kyu/who-is-online/js/online.spec.js -- --watch --verbose
----

